### ISSUE TITLE
s3://s3.amazonaws.com/<bucket name>/ URLs don't work

### ISSUE THREAD

**Issue by mconigliaro** [MayaraCloud/apt-transport-s3#33]
```
Err:3 s3://s3.amazonaws.com/packages.example.com/ubuntu xenial-unstable/main amd64 Packages
  Exception: Can't establish bucket name based on the hostname:              s3.amazonaws.com
```

**Comment by sgotliv** [comment]
@mconigliaro which version of apt-transport-s3 do you have? I had the same problem with 1.2.1 a few hours ago, so I've upgraded to 1.3.0 and problem has disappeared.

**Comment by mconigliaro** [comment]
@sgotliv 1.2.1-1. It's the version in the universe repo for Ubuntu 16.04.

**Comment by krazik** [comment]
is there a format that does work?

**Comment by krazik** [comment]
found it.  `s3://BUCKETNAME.s3.amazonaws.com/`

**Comment by steven-aerts** [comment]
I think this is a duplicate of #32

**Comment by vorlock** [comment]
repo url in apt sources file should be in the format
```
s3://BUCKET_NAME/
```
not the fqdn for vhost type of url, but looks like you figured it out.

Sorry for not looking into it earlier.
