### ISSUE TITLE
Exception on Ubuntu18.04 and v1.3

### ISSUE THREAD

**Issue by jglapa** [MayaraCloud/apt-transport-s3#39]
apt update fails with the following message. It happens on `Ubuntu18.04` where the default version is `1.3.0` (works fine on `Ubuntu16.04` and v `1.2.1`).

```
E: Failed to fetch s3://bucketname.s3-eu-west-1.amazonaws.com/debian/dists/my-dist/all/binary-amd64/Packages  Exception: uri should not include fully qualified domain name for bucket
````

then entry I have:
`deb [trusted=yes] s3://bucketname.s3-eu-west-1.amazonaws.com/debian/ my-dist all`

**Comment by jglapa** [comment]
I got it running by trial & error:
```
deb [trusted=yes] s3://bucketname/debian/ my-dist all
```
and s3auth.conf needs to look like this:
```
AccessKeyId=<placeholder>
SecretAccessKey=<placeholder>
Region=eu-west-1
Token=
```
not sure why this empty `Token=` line is needed?

**Comment by vorlock** [comment]
Looks like you found the solution, I just added some explanation and fixed readme and man page.

Also empty token string was needed for signed urls but we're going to remove it as authv4 is done a bit differently.

So I'm closing this issue but if needed it can be reopened.
